language: node_js
node_js:
- '0.12'
before_install:
- npm install -g bower gulp-cli
after_success:
- git config --global user.name "Travis CI"
- git config --global user.email "$GH_TOKEN"
- export NODE_ENV='production'
- gulp deploy
env:
  global:
    secure: ljVf8CMWn3q0j+59Omel1h84IkxhsKZZegzuiMiteNBizw5Qr6rgdQOXvYRIsJ2BztUSQruHgxgwKQb/Zs9YpkkDnqXzkIHqhfNk+qHp2nf7UjkEr2jJyzO0BF86dANIYjb/vm+h/w2H5p1uzisSKmbCvdCW9TUDiMVRvv9Z/vJuvH65rpF8VjTF7xCba207oQtAKy71Sxt2Wt8oSXC95RGE9/gsqvviEQykOo3CLd4yVERZ51ToqtKAjo/9aEG3DxEAIt0Hl2NNmJV56pG702PMnrPjL0Ekj5wyoCQDqgdyKWj0+PuidNyUSLACUQkTSy30yeP+i7i2jOsk+mfPu7tpVmMD1cbBsjvUUvy1CyFfOkWNj0S11qppNOOgKkdmu9VUOGzUCnP/sGbKyt44ha6X0ZRApeM7XvXpmk4HeCWq2Y4x7jHAKleGVPnu+3/iu8AxKiwngrBWfqjor3pO58P8zK0vMULG51/WqLqCEwKEUsLqBTtGGa3dFyXhWeDkh5uYD/RgQ4Vt/H30WtmF2/Z/ijfQ8z145HiwOtBIBZqJE8Ek6UOpc1lZavx3Y/FApk0hxoUFg3cRZXvPrlTI8rbjmPJutHEe4ZHfVNxcafeP6z9P9d0zoRCVfJ8SCq/4JLQvz49Jc/RyjxyXO2rLcj9Did9M64A/9HZbXk7/mu0
